### ISSUE TITLE
Firing 'DeviceChange' on desktop

### ISSUE THREAD

**Issue by Senths02** [povdocs/webvr-starter-kit#10]
Console message reads:

> "main.min.js:15 THREE.WebGLRenderer 72dev
> main.min.js:15 Uncaught TypeError: Failed to execute 'setPosition' on 'AudioListener': The provided     float value is non-finite."

Chrome: Version 45.0.2454.93 (64-bit)
Mac OSX: 10.8.5

**Comment by brianchirls** [comment]
Thanks for filing. Any idea how to replicate?

**Comment by skompc** [comment]
I got the same issue when I grouped an object and the camera together into a new object then moved the new object

**Comment by brianchirls** [comment]
Can you share some code?

Did you move the camera out of its existing parent? Or did you just add something on to the camera as a child?

**Comment by skompc** [comment]
I can't share code since I'm not able to use my computer atm... But I know that I created a VR.empty object then a VR.box,  I then put the box and the camera as the child of the empty object.. So I guess I moved the camera out of its existing parent (didn't know the camera had a parent)

**Comment by skompc** [comment]
I was trying to make a collision system but guess I failed... I managed tho... Used some three.js mesh related stuff to make due

**Comment by brianchirls** [comment]
Thanks. I tried that, but it's not enough to replicate the problem, and there are a number of potential pitfalls that you may have run into. So I need to see exactly how you did it. Please paste a link or some code when you're back online and have a moment.

**Comment by skompc** [comment]
Forgot to mention I made a movement system... It works fine until u actually move the camera, not just looking around

**Comment by skompc** [comment]
Unfortunately I can't use my computer until I unpack it (I'm about to move so yea)

**Comment by Senths02** [comment]
We are just using panorama in our html: 

> VR.panorama('src');

I've tried two Macbook Pro's (13") running the same version of Chrome and OSX and get the same error. 

It works perfectly on my own Macbook Pro (15" retina Late 2013), same version of Chrome, but I have OSX 10.9.5.

**Comment by Senths02** [comment]
This error is occurring on all of the demos when using the same configuration. Its seem to be related to the threejs audio library.

**Comment by brianchirls** [comment]
@Senths02 I still can't replicate the error. Since you're using Chrome, I'm assuming you're not using an Oculus headset, right?

I just upgraded three.js to the released version 72. See if that helps.

**Comment by Senths02** [comment]
No, just the browser and laptop. Unfortunately the upgrade hasn't had an effect. Did you try it out on OSX 10.8.5? 

Screenshot from 13" Macbook Pro:
![webvr-error](https://cloud.githubusercontent.com/assets/10116682/10017786/34eb2fc6-6129-11e5-88e6-3fd6eb1bd415.jpg)

**Comment by brianchirls** [comment]
Okay, I see what's going on here. It has nothing to do with the OSX version. I'm guessing your MBP is a couple years old and has a hard drive, not an SSD, right?

These MBPs have accelerometers in them so they can detect when you drop them and lock up the hard drive before you hit the ground. Chrome uses this info to generate "deviceorientation" events, which are usually only helpful in mobile devices. My machine has an SSD, so I have to think about where I can get my hands on one like yours so I can debug this and write a workaround.

In the meantime, can you see if this one has the same problem?
http://borismus.github.io/webvr-boilerplate/

**Comment by Senths02** [comment]
That makes sense. Thanks a lot for looking into this. The link you supplied works fine on the machine with hard drive, no errors. 

I'm working on a project for the BBC and wanted to use your library. Is there an email address I could contact you at?

**Comment by brianchirls** [comment]
@Senths02 Can you see if that last commit helped?

Yeah, drop me a line. brian at chirls dot com

**Comment by brianchirls** [comment]
@skompc: I advise against moving the camera off the "body" object. It will cause problems when the HMD moves or rotates to change the view. You can try moving `VR.body.object` under a parent object, but the safest way is to update `VR.body.position` whenever you want to move the viewer around.

In any VR experience, you want to be very careful about how you move the viewer so you don't make them sick.

**Comment by Senths02** [comment]
Thanks Brian! 

I'm not getting any errors and the image comes up, but it still wants to use compass. I get the mobile device icons in the bottom left and you can't pan.

**Comment by brianchirls** [comment]
Okay, how about now? I (with hesitation) added UA parsing to turn off orientation by default on non-mobile devices. You can still turn it back on if you want by clicking the compass icon.

**Comment by Senths02** [comment]
That seems to have done the trick! Thanks a lot!

**Comment by brianchirls** [comment]
Great! Looking forward to hearing about what you're working on via email.
