### ISSUE TITLE
Interference on the Scene from other HTML Elements

### ISSUE THREAD

**Issue by operator1ctg** [povdocs/webvr-starter-kit#11]
I am developing a webpage which utilizes a User Interface(HUDs, divs, spans, paragrpahs, text menus, drop downs, etc...) as an overlay on the scene, which are written in HTML. When interacting with the UI elements, the scene is being effected. (IE: mousedown on a menu/moving a dialog window(jquery), results in teh scene's camera being manipulated as well!)
How can seperate the scene/canvas from the UI/overlay??

thank you in advance! :D

**Comment by brianchirls** [comment]
Okay, this should be fixed now.

But be aware that when your page is viewed in VR mode, either in an Oculus Rift or with Google Cardboard, those UI elements won't be visible. There is work in progress to allow DOM elements in WebVR, but for right now, only the WebGL canvas can be used.
