### ISSUE TITLE
cross origin textures are not loading

### ISSUE THREAD

**Issue by nickdesaulniers** [povdocs/webvr-starter-kit#6]
Guessing something is wrong here, since this conditional is never entered: 
https://github.com/povdocs/webvr-starter-kit/blob/312126c6938bec2618d174c11c8f3639f850b378/src/materials.js#L126-L128

http://jsbin.com/vafiyaniga/edit?js,output

**Comment by brianchirls** [comment]
I assume you're talking about the panorama. The conditional does evaluate properly, but Chrome is sometimes not great about following the source maps in the debugger, so you can't necessarily follow it.

The problem, rather, is that todayifoundout.com is not providing the appropriate headers for cross-origin image access. Try hosting the image on imgur.com or another server that you're certain will offer the correct response headers.

Also, the image is not an equirectangular spherical photo, so even if it does load, it's not going to be a proper sky sphere.

**Comment by nickdesaulniers** [comment]
oops!
